/*
 *Create table Script (Oracle )
 *


 * Oracle10g Release 10.2.0.1.0 (for Linux)
 * Oracle10g Release 10.2.0.1.0 (for Windows XP)
 */

--
CREATE TABLE PRODUCTLIST (
    PRODUCTID     NUMBER NOT NULL,
    PRODUCTNAME     VARCHAR2(30) NOT NULL,
    GROUPNAME VARCHAR2(20) NOT NULL,
    COSTS   NUMBER,
    PRISE     NUMBER,
    CONSTRAINT pk_s1 PRIMARY KEY (PRODUCTID)
);

--
CREATE TABLE ASSISTANTLIST (
    ASSISTANTID   NUMBER NOT NULL,
    ASSISTANTNAME   VARCHAR2(20) NOT NULL,
    ENGLISHNAME   VARCHAR2(20) NOT NULL,
    MGR_ID     NUMBER,
    BIRTHDAY   DATE NOT NULL,
    GENDER       NUMBER NOT NULL,
    CONSTRAINT pk_t1 PRIMARY KEY (ASSISTANTID),
    CONSTRAINT fk_m1 FOREIGN KEY (MGR_ID) REFERENCES ASSISTANTLIST(ASSISTANTID),
    CONSTRAINT ck_g1 CHECK (GENDER=0 OR GENDER=1)
);

--
CREATE TABLE GUESTLIST (
    GUESTID     NUMBER NOT NULL,
    GUESTNAME     VARCHAR2(20) NOT NULL,
    ADDRESS     VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_k1 PRIMARY KEY (GUESTID)
);

--
CREATE TABLE SALEDATA (
    RECEIPTSID   NUMBER NOT NULL,
    LINEID     NUMBER NOT NULL,
    DATEZ     DATE NOT NULL,
    PRODUCTID     NUMBER NOT NULL,
    ASSISTANTID   NUMBER NOT NULL,
    GUESTID     NUMBER NOT NULL,
    QUANTITY       NUMBER NOT NULL,
    CONSTRAINT pk_u1 PRIMARY KEY (RECEIPTSID, LINEID),
    CONSTRAINT fk_s1 FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTLIST(PRODUCTID),
    CONSTRAINT fk_t1 FOREIGN KEY (ASSISTANTID) REFERENCES ASSISTANTLIST(ASSISTANTID),
    CONSTRAINT fk_k1 FOREIGN KEY (GUESTID) REFERENCES GUESTLIST(GUESTID)
);

--
CREATE TABLE SUBASSISTANTLIST (
    SUBASSISTANTID   NUMBER NOT NULL,
    SUBASSISTANTNAME   VARCHAR2(20) NOT NULL,
    ENGLISHNAME   VARCHAR2(20) NOT NULL,
    MGR_ID     NUMBER,
    BIRTHDAY   DATE NOT NULL,
    GENDER       NUMBER NOT NULL,
    CONSTRAINT pk_siten_t1 PRIMARY KEY (SUBASSISTANTID),
    CONSTRAINT fk_siten_m1 FOREIGN KEY (MGR_ID) REFERENCES SUBASSISTANTLIST(SUBASSISTANTID),
    CONSTRAINT ck_siten_g1 CHECK (GENDER=0 OR GENDER=1)
);
